#![recursion_limit = "1024"]

pub mod acoustic;
pub mod audio;
pub mod autostart;
pub mod config;
pub mod dictionary;
pub mod enrich;
pub mod hardware;
pub mod history;
pub mod hotkey;
pub mod license;
pub mod model_manager;
pub mod notify;
pub mod onboarding;
pub mod overlay;
pub mod paste;
pub mod permissions;
pub mod report;
pub mod state;
pub mod templates;
pub mod transcribe;
pub mod tray;
pub mod updater;
pub mod util;
